### ISSUE TITLE
Random Event roll

### ISSUE THREAD

**Issue by villChurch** [villChurch/ribbon-bot#35]
Random Event Rolls - pretty basic concept. Basically an RNG line output. I would like to be able to set up lists of phrases, words, whatever and then request a randomly chosen output she displays. It would be for RP written form Events like our Mustang Makeover.

So for example. I want to assign everyone's pony for the event a personality. I somehow give RB a list. Then I make a command /roll ponypersonality and it outputs one line from the ponypersonality list. Radishbooty: Your pony has a lazy personality. Later, they have a "Vet Visit" day and I go on their storyboard and do /roll ponyvetcheck and it outputs a line from that list. Radishbooty: Your pony has a sprained ankle.

https://discord.com/channels/565016829131751425/745012634889355264/1197675274523914250

**Comment by Epona142** [comment]
Thoughts since then - deff want it to target a user on output, since I decided I'm going to do all the rolls in one channel (at least for this event), so a ping would be helpful for them. 

So basically, 
/roll @user eventlist
RB: @user random line from eventlist

Would need to make different types of Event Lists, with short phrases to output. Eg:
/roll @epona ponyvetcheck
RB: @epona The vet finds that your pony has a sore front hoof.
